name: Pipeline Lint

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21.7.3'

      - name: Install dependencies
        run: npm install

      - name: Check commit message for skip-tests
        id: check_skip_tests
        run: |
           if git rev-list -1 HEAD | xargs -I {} git log --format=%B -n 1 {} | grep -q '\[skip-tests\]'; then
            echo "Skipping coverage analysis due to [skip-tests] tag in commit message"
            echo "RUN_TESTS=false" >> $GITHUB_ENV
          else
            echo "RUN_TESTS=true" >> $GITHUB_ENV
          fi

      - name: Run linter
        run: npm run lint

      - name: Debug RUN_TESTS
        run: echo "RUN_TESTS is set to $RUN_TESTS"
        env:
          RUN_TESTS: ${{ env.RUN_TESTS }}

      - name: Run unit tests
        if: env.RUN_TESTS == 'true'
        run: npm test
